# Generated by Django 4.1.2 on 2023-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='client_image/')),
                ('short_des', models.TextField(default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clinets',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
                ('msg', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('company', models.CharField(default=' ', max_length=50)),
                ('feedback_des', models.TextField(max_length=200)),
                ('profile_pic', models.ImageField(upload_to='feedback_images/')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('cover_image', models.ImageField(upload_to='project_cover/')),
                ('short_des', models.TextField(default='', max_length=120)),
                ('long_des', models.TextField(default='', max_length=250)),
                ('category', models.CharField(choices=[('mobile', 'Mobile Development'), ('web', 'Web Development'), ('landing', 'Web Landing Page')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
